server:
  port: 8082
spring:
  application:
    name: SafeKeyboard
  datasource:
    url: jdbc:mysql://localhost:3306/user?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
base:
  messages:
    type: database # bundle or database
    values-bundles:
      basename: classpath:config/msg/server-values,classpath:config/msg/values
      cache-duration: PT1H
    errors-bundles:
      basename: classpath:config/msg/server-errors,classpath:config/msg/errors
      cache-duration: PT1H
    values-tables:
      basename: values_messages
      cache-duration: PT10M
    errors-tables:
      basename: error_messages
      cache-duration: PT10M