server:
  port: 8082
spring:
  application:
    name: SafeKeyboard
  datasource:
    url: jdbc:mysql://localhost:3306/user?useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root